import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextHero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex justify-evenly">
            <li>Home</li>
            <li>About</li>
            <li>Service</li>
          </ul>
        </nav>
        {children}
        <footer>
          <p className="text-center">
            All right reserved to Creators of NextHero
          </p>
        </footer>
      </body>
    </html>
  );
}
